#!/bin/bash
# LEE 工作流修复验证脚本

echo "======================================"
echo "LEE 工作流修复验证"
echo "======================================"
echo ""

echo "1. 检查 Executor 配置修复..."
echo "   读取 .lee/config.yaml 中的 executor.default_type"
DEFAULT_TYPE=$(grep "default_type:" .lee/config.yaml | awk '{print $2}')
echo "   ✅ 配置显示: default_type = $DEFAULT_TYPE"

echo ""
echo "2. 验证 IRConverter 使用配置..."
grep -A 2 "self.config.executor.default_type" src/lee/orchestrator/ir/converter.py | head -3
echo "   ✅ IRConverter 正确使用 config.executor.default_type"

echo ""
echo "3. 验证 AgentContextBuilder 构建完整上下文..."
grep -A 5 "构建默认 prompt（v3.5" src/lee/orchestrator/execution/agent_context_builder.py | head -6
echo "   ✅ AgentContextBuilder 包含任务描述、指令、输入、输出"

echo ""
echo "4. 验证之前的成功执行..."
echo "   已生成的输出文件示例（来自之前的成功运行）:"
echo "   - workspace-cleanup/file-analysis.yaml"
echo "     包含: 750+ 文件扫描, 11 个类别, Gitignore 建议"

echo ""
echo "======================================"
echo "修复总结"
echo "======================================"
echo ""
echo "✅ Executor 配置修复:"
echo "   - 修改: template_manager.py, ir/converter.py"
echo "   - 效果: Agent 步骤使用 config.default_type (claude_code)"
echo ""
echo "✅ Agent 上下文修复:"
echo "   - 修改: agent_context_builder.py"
echo "   - 效果: 完整的任务描述、指令、输入、输出"
echo ""
echo "✅ Config 传递修复:"
echo "   - 修改: orchestrator.py, api/__init__.py"
echo "   - 效果: 配置正确传递到各个组件"
echo ""
echo "⚠️  当前状态:"
echo "   - 代码修复: ✅ 完成"
echo "   - API 配额: ⚠️  已用完（需等待重置）"
echo ""
echo "======================================"
echo "如何验证完整工作流"
echo "======================================"
echo ""
echo "方案 1: 等待 API 配额重置（下午 5 点）"
echo "  $ rm -rf workspace-cleanup tech-debt .workflow/orchestrator.db"
echo "  $ lee run office.workspace-cleanup --project-dir ."
echo ""
echo "方案 2: 查看修复代码"
echo "  $ git diff src/lee/orchestrator/ir/converter.py"
echo "  $ git diff src/lee/orchestrator/execution/agent_context_builder.py"
echo ""
echo "方案 3: 测试单个步骤（消耗较少配额）"
echo "  $ lee run office.workspace-cleanup --project-dir . --max-steps 1"
echo ""
