#!/usr/bin/env python
"""
Install Git Hooks

安装 Git hooks 到本地仓库，实现 commit/push 时的自动检查。

用法:
    python scripts/install-git-hooks.py

卸载:
    python scripts/install-git-hooks.py --uninstall
"""

import os
import shutil
import sys
from pathlib import Path


GIT_DIR = Path(".git")
HOOKS_DIR = GIT_DIR / "hooks"
SCRIPTS_DIR = Path("scripts")

HOOKS = {
    "pre-commit": "git-pre-commit-hook.py",
    "pre-push": "git-pre-push-hook.py",
}


def is_git_repo() -> bool:
    """检查当前目录是否是 Git 仓库"""
    return GIT_DIR.exists()


def install_hook(hook_name: str, script_name: str) -> bool:
    """
    安装单个 hook
    
    Args:
        hook_name: hook 名称（如 pre-commit）
        script_name: 脚本文件名
    
    Returns:
        安装是否成功
    """
    script_path = SCRIPTS_DIR / script_name
    hook_path = HOOKS_DIR / hook_name
    
    if not script_path.exists():
        print(f"⚠️  脚本不存在：{script_path}")
        return False
    
    # 创建 hooks 目录（如果不存在）
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    
    # 创建 hook 脚本（包装器）
    # 使用 Python 直接调用，避免 shebang 问题
    hook_content = f'''#!/bin/sh
# Git {hook_name} hook - auto-generated by install-git-hooks.py
# DO NOT EDIT MANUALLY

# 获取脚本所在目录
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# 切换到仓库根目录
cd "$REPO_ROOT"

# 运行 Python 检查脚本
python "{script_path.resolve()}"
exit_code=$?

# 如果检查失败，阻止操作
if [ $exit_code -ne 0 ]; then
    echo ""
    echo "💡 提示：可以使用 --no-verify 跳过 hooks（不推荐）"
    echo "   git commit --no-verify"
    echo "   git push --no-verify"
    exit $exit_code
fi
'''
    
    try:
        # 如果已有 hook，备份
        if hook_path.exists():
            backup_path = hook_path.with_suffix(f".{hook_name}.bak")
            shutil.copy2(hook_path, backup_path)
            print(f"💾 已备份现有 hook: {backup_path}")
        
        # 写入 hook
        hook_path.write_text(hook_content, encoding="utf-8")
        
        # 设置执行权限（Unix-like 系统）
        if os.name != "nt":
            os.chmod(hook_path, 0o755)
        
        return True
    
    except Exception as e:
        print(f"❌ 安装失败：{e}")
        return False


def uninstall_hook(hook_name: str) -> bool:
    """
    卸载单个 hook
    
    Args:
        hook_name: hook 名称
    
    Returns:
        卸载是否成功
    """
    hook_path = HOOKS_DIR / hook_name
    
    if not hook_path.exists():
        print(f"⚠️  Hook 不存在：{hook_path}")
        return True
    
    try:
        hook_path.unlink()
        return True
    except Exception as e:
        print(f"❌ 卸载失败：{e}")
        return False


def install_all() -> bool:
    """安装所有 hooks"""
    print("🔧 安装 Git hooks...")
    print()
    
    if not is_git_repo():
        print("❌ 当前目录不是 Git 仓库")
        print(f"   请确保在仓库根目录运行此脚本（需要 .git 目录）")
        return False
    
    success = True
    
    for hook_name, script_name in HOOKS.items():
        print(f"📌 安装 {hook_name} hook...")
        if install_hook(hook_name, script_name):
            print(f"   ✅ {hook_name} 安装成功")
        else:
            print(f"   ❌ {hook_name} 安装失败")
            success = False
        print()
    
    print("=" * 60)
    if success:
        print("✅ 所有 Git hooks 安装成功")
        print()
        print("📋 已安装的 hooks:")
        for hook_name in HOOKS:
            print(f"   - .git/hooks/{hook_name}")
        print()
        print("📖 使用说明:")
        print("   - commit 时自动检查硬编码路径")
        print("   - push 时自动检查 L3 模板规范")
        print()
        print("🚫 临时跳过 hooks（不推荐）:")
        print("   git commit --no-verify")
        print("   git push --no-verify")
    else:
        print("❌ 部分 hooks 安装失败")
    
    return success


def uninstall_all() -> bool:
    """卸载所有 hooks"""
    print("🔧 卸载 Git hooks...")
    print()
    
    if not is_git_repo():
        print("❌ 当前目录不是 Git 仓库")
        return False
    
    success = True
    
    for hook_name in HOOKS:
        print(f"📌 卸载 {hook_name} hook...")
        if uninstall_hook(hook_name):
            print(f"   ✅ {hook_name} 卸载成功")
        else:
            print(f"   ❌ {hook_name} 卸载失败")
            success = False
        print()
    
    print("=" * 60)
    if success:
        print("✅ 所有 Git hooks 卸载成功")
    else:
        print("❌ 部分 hooks 卸载失败")
    
    return success


def show_status() -> None:
    """显示 hooks 安装状态"""
    print("📊 Git hooks 安装状态:")
    print()
    
    if not is_git_repo():
        print("❌ 当前目录不是 Git 仓库")
        return
    
    for hook_name, script_name in HOOKS.items():
        hook_path = HOOKS_DIR / hook_name
        script_path = SCRIPTS_DIR / script_name
        
        hook_installed = "✅" if hook_path.exists() else "❌"
        script_exists = "✅" if script_path.exists() else "❌"
        
        print(f"   {hook_name}:")
        print(f"      Hook 文件：{hook_installed} {'已安装' if hook_path.exists() else '未安装'}")
        print(f"      脚本文件：{script_exists} {'存在' if script_path.exists() else '缺失'}")
        print()


def main():
    """主函数"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="安装/卸载 Git hooks"
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="卸载所有 hooks"
    )
    parser.add_argument(
        "--status",
        action="store_true",
        help="显示 hooks 安装状态"
    )
    
    args = parser.parse_args()
    
    if args.status:
        show_status()
        sys.exit(0)
    
    if args.uninstall:
        success = uninstall_all()
    else:
        success = install_all()
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
